# Generated by Django 4.0 on 2022-01-07 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('main', '0004_favorites'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorites',
            unique_together={('post', 'user')},
        ),
    ]
